### ISSUE TITLE
Remove deployed app

### ISSUE THREAD

**Issue by oneingan** [Ninlives/relocatable.nix#1]
I deploy a bundle generated by relocatable.nix in the work directory, I'm trying to remove it but permission denied, same thing if I'm using root. Any hints? I'm wondering if it is nix-daemon related, but AFAIK deployment is Nix installation independent.

**Comment by Ninlives** [comment]
The bundled app itself has nothing to do with nix, I currently have no idea about the problem. Do you have a screen shot of what happened?

Edit: try to set write permission bits on deployed files before removing.

**Comment by oneingan** [comment]
Sure!

Write permission solve it. Weird, I dont remember other situation where root cares about user permissions.
